name: Deploy Terraform Workload Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  #ENVIRONMENT: dev
  ARM_CLIENT_ID: c376f14f-2994-4ed9-8df1-9e3d1087d749
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: a83145a3-215b-44a4-9387-a540faaa58e9
  ARM_TENANT_ID: 040886fa-09b0-4e7f-8cad-9e9797dd96a0

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
      
      - run: terraform init

      - id: plan
        run: terraform plan -no-color -out="tfplan" -var-file="$ENVIRONMENT.tfvars"

      - id: apply
        run: terraform apply "tfplan" -no-color

      # - run: echo ${{ steps.plan.outputs.stdout }}
      # - run: echo ${{ steps.plan.outputs.stderr }}
      # - run: echo ${{ steps.plan.outputs.exitcode }}
